default:
  app_name: ETVapp
  app_version: !expr as.character(utils::packageVersion("ETVapp"))
  app_date: !expr as.character(utils::packageDate("ETVapp"))
  app_prod: no
  bam_server: false
production:
  app_prod: yes
dev:
  app_version: development
  app_date: !expr as.character(Sys.Date())
